In [1]:
import torch
import torch.nn as nn

In [2]:
# one way to make some typical input:
input = torch.randn( 1, 3 )
input

tensor([[-0.0549,  0.6530,  0.0190]])

In [3]:
input = torch.tensor([[ 1.0, 2.0, 3.0 ]])
input

tensor([[1., 2., 3.]])

In [4]:
# a simple neural network:
model = nn.Sequential(
    # a layer that takes 3 inputs, gives 2 outputs
    nn.Linear( 3, 2 ),
    # a nonlinear activation function
    nn.ReLU(),
    # output layer takes 2 inputs, gives scalar output
    nn.Linear( 2, 1)
)

In [5]:
model[0].weight.data = torch.tensor([[ 2.0, 1.0, -1.0 ],
                                     [ -2.0, -1.0, 1.0 ]])
model[0].weight.data

tensor([[ 2.,  1., -1.],
        [-2., -1.,  1.]])

In [6]:
model[0].bias.data = torch.tensor([[0.0, 0.0]])

In [7]:
input @ model[0].weight.data.T + model[0].bias.data

tensor([[ 1., -1.]])

In [8]:
activation = nn.ReLU()
middle = activation( input @ model[0].weight.data.T + model[0].bias.data)
middle

tensor([[1., 0.]])

In [9]:
middle @ model[2].weight.data.T + model[2].bias.data

tensor([[-0.2890]])

In [10]:
model(input)

tensor([[-0.2890]], grad_fn=<AddmmBackward0>)