In [23]:
import torch
import tiktoken

In [24]:
tokenizer = tiktoken.get_encoding('gpt2')

In [25]:
raw = 'So threatening had become the general aspect of affairs, that the king thought it prudent to send his son' 

In [26]:
enc = tokenizer.encode(raw)
print(enc)

[2396, 11123, 550, 1716, 262, 2276, 4843, 286, 9674, 11, 326, 262, 5822, 1807, 340, 34998, 284, 3758, 465, 3367]


In [27]:
ret = tokenizer.decode(enc)
print(ret)

So threatening had become the general aspect of affairs, that the king thought it prudent to send his son


In [28]:
vocab_size = 4
output_dimension = 8
inputs = torch.nn.Embedding(vocab_size, output_dimension)
print(inputs.weight)

inputs = inputs.weight.data
print(inputs) # get the same answer without the 'requires_grad+True'

Parameter containing:
tensor([[ 2.4372e-03,  5.4385e-01,  7.5320e-04,  5.5419e-01, -2.4587e+00,
         -2.5192e-01,  6.1233e-01,  3.2426e-01],
        [-5.0827e-01,  8.9565e-01, -5.3059e-01,  4.1679e-01, -6.1498e-01,
         -1.5292e-01, -4.9243e-01, -2.1665e-01],
        [-7.5124e-01, -1.7398e+00,  1.1536e+00,  6.6208e-01, -3.6198e-01,
          8.8740e-01, -1.2515e+00,  9.2859e-01],
        [-1.1090e+00, -1.5436e+00,  1.5929e+00,  7.5034e-01,  8.8006e-02,
          6.3715e-01, -2.3153e-01, -1.2820e+00]], requires_grad=True)
tensor([[ 2.4372e-03,  5.4385e-01,  7.5320e-04,  5.5419e-01, -2.4587e+00,
         -2.5192e-01,  6.1233e-01,  3.2426e-01],
        [-5.0827e-01,  8.9565e-01, -5.3059e-01,  4.1679e-01, -6.1498e-01,
         -1.5292e-01, -4.9243e-01, -2.1665e-01],
        [-7.5124e-01, -1.7398e+00,  1.1536e+00,  6.6208e-01, -3.6198e-01,
          8.8740e-01, -1.2515e+00,  9.2859e-01],
        [-1.1090e+00, -1.5436e+00,  1.5929e+00,  7.5034e-01,  8.8006e-02,
          6.3715e-01, 

In [29]:
inputs.shape

torch.Size([4, 8])

In [30]:
for row in inputs:
    print(row.tolist())

[0.0024372003972530365, 0.5438529849052429, 0.000753197877202183, 0.5541906356811523, -2.458731174468994, -0.25192269682884216, 0.6123308539390564, 0.3242608904838562]
[-0.5082664489746094, 0.8956487774848938, -0.5305865406990051, 0.41678571701049805, -0.6149751543998718, -0.15291960537433624, -0.49242523312568665, -0.21665015816688538]
[-0.7512362599372864, -1.7397701740264893, 1.153609037399292, 0.6620757579803467, -0.36197948455810547, 0.8874033689498901, -1.2514982223510742, 0.9285872578620911]
[-1.1089531183242798, -1.5435950756072998, 1.5928676128387451, 0.7503377795219421, 0.08800597488880157, 0.6371463537216187, -0.23152561485767365, -1.2819617986679077]


In [31]:
x = torch.Tensor([1.1, 2.3])
y = torch.Tensor([3.4, -2.1])

In [32]:
print(torch.dot(x, y))

print(1.1 * 3.4 + 2.3 * (-2.1))

tensor(-1.0900)
-1.0899999999999999


In [33]:
query = inputs[2]
print(query)

tensor([-0.7512, -1.7398,  1.1536,  0.6621, -0.3620,  0.8874, -1.2515,  0.9286])


In [34]:
for i in range(len(inputs)):
    print(torch.dot(query, inputs[i]))

tensor(-0.3790)
tensor(-1.0105)
tensor(8.7073)
tensor(5.4858)


In [35]:
att_scores2 = torch.zeros(len(inputs))
for i in range(len(inputs)):
    att_scores2[i] = torch.dot(query, inputs[i])

print(att_scores2)

tensor([-0.3790, -1.0105,  8.7073,  5.4858])


In [36]:
att_weights2 = torch.softmax(att_scores2, dim = 0) # torch.exp(x)/ torch.exp(x).sum()
print(att_weights2)

tensor([1.0884e-04, 5.7878e-05, 9.6148e-01, 3.8357e-02])


In [37]:
att_weights2.sum()

tensor(1.)

In [38]:
context_vector2 = torch.zeros(query.shape)
for i in range(len(att_weights2)):
    context_vector2 += att_weights2[i] * inputs[i]
print(context_vector2)

tensor([-0.7649, -1.7318,  1.1702,  0.6654, -0.3450,  0.8776, -1.2121,  0.8437])


In [39]:
print(inputs)
print(inputs.T) # flips axes

tensor([[ 2.4372e-03,  5.4385e-01,  7.5320e-04,  5.5419e-01, -2.4587e+00,
         -2.5192e-01,  6.1233e-01,  3.2426e-01],
        [-5.0827e-01,  8.9565e-01, -5.3059e-01,  4.1679e-01, -6.1498e-01,
         -1.5292e-01, -4.9243e-01, -2.1665e-01],
        [-7.5124e-01, -1.7398e+00,  1.1536e+00,  6.6208e-01, -3.6198e-01,
          8.8740e-01, -1.2515e+00,  9.2859e-01],
        [-1.1090e+00, -1.5436e+00,  1.5929e+00,  7.5034e-01,  8.8006e-02,
          6.3715e-01, -2.3153e-01, -1.2820e+00]])
tensor([[ 2.4372e-03, -5.0827e-01, -7.5124e-01, -1.1090e+00],
        [ 5.4385e-01,  8.9565e-01, -1.7398e+00, -1.5436e+00],
        [ 7.5320e-04, -5.3059e-01,  1.1536e+00,  1.5929e+00],
        [ 5.5419e-01,  4.1679e-01,  6.6208e-01,  7.5034e-01],
        [-2.4587e+00, -6.1498e-01, -3.6198e-01,  8.8006e-02],
        [-2.5192e-01, -1.5292e-01,  8.8740e-01,  6.3715e-01],
        [ 6.1233e-01, -4.9243e-01, -1.2515e+00, -2.3153e-01],
        [ 3.2426e-01, -2.1665e-01,  9.2859e-01, -1.2820e+00]])


In [40]:
attention_scores = inputs @ inputs.T
print(attention_scores)

tensor([[ 7.1918,  1.8952, -0.3790, -1.3595],
        [ 1.8952,  2.2068, -1.0105, -1.1111],
        [-0.3790, -1.0105,  8.7073,  5.4858],
        [-1.3595, -1.1111,  5.4858,  8.8234]])


In [41]:
attention_weights = torch.softmax( attention_scores, dim = -1 )
print(attention_weights)

tensor([[9.9432e-01, 4.9802e-03, 5.1234e-04, 1.9219e-04],
        [4.0491e-01, 5.5290e-01, 2.2151e-02, 2.0032e-02],
        [1.0884e-04, 5.7878e-05, 9.6148e-01, 3.8357e-02],
        [3.6510e-05, 4.6805e-05, 3.4300e-02, 9.6562e-01]])


In [42]:
print(attention_weights[0].sum())

tensor(1.0000)


In [43]:
context_vectors = attention_weights @ inputs
print(context_vectors)

tensor([[-7.0594e-04,  5.4403e-01, -9.9635e-04,  5.5360e-01, -2.4480e+00,
         -2.5068e-01,  6.0571e-01,  3.2157e-01],
        [-3.1889e-01,  6.4596e-01, -2.3560e-01,  4.8454e-01, -1.3419e+00,
         -1.5414e-01, -5.6682e-02,  6.4005e-03],
        [-7.6486e-01, -1.7318e+00,  1.1702e+00,  6.6544e-01, -3.4496e-01,
          8.7762e-01, -1.2121e+00,  8.4367e-01],
        [-1.0966e+00, -1.5501e+00,  1.5776e+00,  7.4729e-01,  7.2446e-02,
          6.4566e-01, -2.6649e-01, -1.2060e+00]])
