In [1]:
import torch
import tiktoken

In [2]:
tokenizer = tiktoken.get_encoding('gpt2')

In [3]:
raw = 'So threatening had become the general aspect of affairs, that the king thought it prudent to send his son' 

In [4]:
enc = tokenizer.encode(raw)
print(enc)

[2396, 11123, 550, 1716, 262, 2276, 4843, 286, 9674, 11, 326, 262, 5822, 1807, 340, 34998, 284, 3758, 465, 3367]


In [5]:
ret = tokenizer.decode(enc)
print(ret)

So threatening had become the general aspect of affairs, that the king thought it prudent to send his son


In [6]:
vocab_size = 4
output_dimension = 8
inputs = torch.nn.Embedding(vocab_size, output_dimension)
print(inputs.weight)

inputs = inputs.weight.data
print(inputs) # get the same answer without the 'requires_grad+True'

Parameter containing:
tensor([[-0.0305,  3.3796, -2.5016, -1.2036,  0.2799,  2.1263,  0.1639,  0.2492],
        [ 0.1527, -0.9483, -2.0567, -1.0204, -1.3837, -0.6000,  0.3184,  1.3188],
        [-0.0505,  0.4629,  0.0268,  1.6601, -0.7094,  0.4188,  0.8855,  0.3651],
        [ 1.6156,  0.2851, -0.6711, -0.3790,  0.7342, -0.9215,  0.5173,  0.1448]],
       requires_grad=True)
tensor([[-0.0305,  3.3796, -2.5016, -1.2036,  0.2799,  2.1263,  0.1639,  0.2492],
        [ 0.1527, -0.9483, -2.0567, -1.0204, -1.3837, -0.6000,  0.3184,  1.3188],
        [-0.0505,  0.4629,  0.0268,  1.6601, -0.7094,  0.4188,  0.8855,  0.3651],
        [ 1.6156,  0.2851, -0.6711, -0.3790,  0.7342, -0.9215,  0.5173,  0.1448]])


In [7]:
inputs.shape

torch.Size([4, 8])

In [8]:
for row in inputs:
    print(row.tolist())

[-0.030461864545941353, 3.379633665084839, -2.501620292663574, -1.2035605907440186, 0.27994439005851746, 2.1263039112091064, 0.1639443337917328, 0.2492324411869049]
[0.15265977382659912, -0.9482561349868774, -2.0567238330841064, -1.020434856414795, -1.383724331855774, -0.5999849438667297, 0.3184005320072174, 1.3187685012817383]
[-0.050488781183958054, 0.462890625, 0.02684025652706623, 1.660145878791809, -0.7093648314476013, 0.41878703236579895, 0.8855202794075012, 0.36512529850006104]
[1.6156370639801025, 0.28505197167396545, -0.6710654497146606, -0.37897810339927673, 0.7341901659965515, -0.9214617609977722, 0.5172808766365051, 0.14476490020751953]


In [9]:
x = torch.Tensor([1.1, 2.3])
y = torch.Tensor([3.4, -2.1])

In [10]:
print(torch.dot(x, y))

print(1.1 * 3.4 + 2.3 * (-2.1))

tensor(-1.0900)
-1.0899999999999999


In [11]:
query = inputs[2]
print(query)

tensor([-0.0505,  0.4629,  0.0268,  1.6601, -0.7094,  0.4188,  0.8855,  0.3651])


In [12]:
for i in range(len(inputs)):
    print(torch.dot(query, inputs[i]))

tensor(0.4288)
tensor(-0.7022)
tensor(4.5697)
tensor(-0.9926)


In [ ]:
# initiate a list of tensors with length of rows in inputs that has zeros as values and stores scores after loop
att_scores2 = torch.zeros(len(inputs))
for i in range(len(inputs)):
    att_scores2[i] = torch.dot(query, inputs[i])

print(att_scores2)

tensor([ 0.4288, -0.7022,  4.5697, -0.9926])


In [ ]:
# scores + normaliazation = weights
att_weights2 = torch.softmax(att_scores2, dim = 0) # torch.exp(x)/ torch.exp(x).sum()
print(att_weights2)

tensor([0.0155, 0.0050, 0.9757, 0.0037])


In [15]:
att_weights2.sum()

tensor(1.0000)

In [16]:
context_vector2 = torch.zeros(query.shape)
for i in range(len(att_weights2)):
    context_vector2 += att_weights2[i] * inputs[i]
print(context_vector2)

tensor([-0.0429,  0.5004, -0.0255,  1.5946, -0.6920,  0.4352,  0.8701,  0.3673])


In [17]:
print(inputs)
print(inputs.T) # flips axes

tensor([[-0.0305,  3.3796, -2.5016, -1.2036,  0.2799,  2.1263,  0.1639,  0.2492],
        [ 0.1527, -0.9483, -2.0567, -1.0204, -1.3837, -0.6000,  0.3184,  1.3188],
        [-0.0505,  0.4629,  0.0268,  1.6601, -0.7094,  0.4188,  0.8855,  0.3651],
        [ 1.6156,  0.2851, -0.6711, -0.3790,  0.7342, -0.9215,  0.5173,  0.1448]])
tensor([[-0.0305,  0.1527, -0.0505,  1.6156],
        [ 3.3796, -0.9483,  0.4629,  0.2851],
        [-2.5016, -2.0567,  0.0268, -0.6711],
        [-1.2036, -1.0204,  1.6601, -0.3790],
        [ 0.2799, -1.3837, -0.7094,  0.7342],
        [ 2.1263, -0.6000,  0.4188, -0.9215],
        [ 0.1639,  0.3184,  0.8855,  0.5173],
        [ 0.2492,  1.3188,  0.3651,  0.1448]])


In [ ]:
# Matrix multiplication of the inputs to get att scores of the whole thing
attention_scores = inputs @ inputs.T
print(attention_scores)

tensor([[23.8180,  1.8817,  0.4288,  1.4161],
        [ 1.8817, 10.3091, -0.7022,  1.6358],
        [ 0.4288, -0.7022,  4.5697, -0.9926],
        [ 1.4161,  1.6358, -0.9926,  4.9622]])


In [19]:
attention_weights = torch.softmax( attention_scores, dim = -1 )
print(attention_weights)

tensor([[1.0000e+00, 2.9727e-10, 6.9529e-11, 1.8663e-10],
        [2.1869e-04, 9.9959e-01, 1.6508e-05, 1.7103e-04],
        [1.5522e-02, 5.0096e-03, 9.7572e-01, 3.7469e-03],
        [2.7019e-02, 3.3657e-02, 2.4299e-03, 9.3689e-01]])


In [23]:
print(attention_weights[0].sum())
print(attention_weights[1].sum())
print(attention_weights[2].sum())
print(attention_weights[3].sum())

tensor(1.)
tensor(1.)
tensor(1.0000)
tensor(1.)


In [ ]:
# Again, matrix multiplication of all weights with inputs to get the context vectors (automatically summed into the list)
context_vectors = attention_weights @ inputs
print(context_vectors)

tensor([[-0.0305,  3.3796, -2.5016, -1.2036,  0.2799,  2.1263,  0.1639,  0.2492],
        [ 0.1529, -0.9471, -2.0565, -1.0203, -1.3830, -0.5994,  0.3184,  1.3183],
        [-0.0429,  0.5004, -0.0255,  1.5946, -0.6920,  0.4352,  0.8701,  0.3673],
        [ 1.5179,  0.3276, -0.7655, -0.4179,  0.6471, -0.8250,  0.5019,  0.1876]])
